# Generated by Django 5.1.3 on 2025-05-24 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedifyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherpincodemappeddata',
            name='weather_data',
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 12, 14, 17, 952710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='24-05-2025 05:44:17 AM', max_length=200),
        ),
    ]
