# Generated by Django 5.1.3 on 2025-05-24 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedifyApp', '0003_alter_authtoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherpincodemappeddata',
            name='weather_data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 12, 35, 27, 351456, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='24-05-2025 06:05:27 AM', max_length=200),
        ),
    ]
