# Generated by Django 5.1.3 on 2025-05-24 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedifyApp', '0004_weatherpincodemappeddata_weather_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='pictures')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(null=True, upload_to='files')),
            ],
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 24, 14, 54, 0, 300666, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='scheduleitemlist',
            name='lastScheduleOn',
            field=models.CharField(default='24-05-2025 08:24:00 AM', max_length=200),
        ),
    ]
